---
# This playbook deploys a new EC2 instance

- hosts: localhost
  connection: local
  gather_facts: False
  vars_prompt:
    - name: vpc_id
      prompt: VPC id
      private: no
      default: vpc-d8c0f4bc
    - name: subnet_id
      prompt: Subnet id
      private: no
      default: subnet-b68a16c0
  tasks:
    #LA_TODO- name: Create EC2 Security Group
    #LA_TODO  ec2_group:
    #LA_TODO    name: ghuser-sg
    #LA_TODO    description: ghuser
    #LA_TODO    region: "{{ aws_region }}"
    #LA_TODO    vpc_id: "{{ vpc_id }}"
    #LA_TODO    rules:
    #LA_TODO      - proto: tcp
    #LA_TODO        from_port: 22
    #LA_TODO        to_port: 22
    #LA_TODO        cidr_ip: 0.0.0.0/0
    - name: Create EC2 instance
      ec2:
        key_name: "{{ instance_name }}"
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        group: "default,ghuser-sg"
        image: ami-759bc50a # Ubuntu 16.04 hvm:ebs-ssd

        # Note: if you want to build the Reframe web app, you'll need at least 2GB RAM (t2.small)
        instance_type: t2.small #LA_TODO t2.nano

        wait: true
        instance_tags:
          Name: "{{ instance_name }}"
      register: created_instance
    - add_host:
        hostname: "{{ created_instance.instances[0].public_ip }}"
        groupname: created_instance
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ created_instance.instances[0].public_ip }}"
        port: 22

- hosts: created_instance
  gather_facts: True
  user: ubuntu
  vars_prompt:
    - name: git_name
      prompt: Git name
      private: no
      default: Aurelien Lourot
    - name: git_email
      prompt: Git email
      private: no
      default: aurelien.lourot@gmail.com
    - name: github_client_id
      prompt: GitHub client id (e.g. 0123456789abcdef0123)
      private: no
    - name: github_client_secret
      prompt: GitHub client secret (e.g. 0123456789abcdef0123456789abcdef01234567)
      private: yes
    - name: github_username
      prompt: GitHub username
      private: no
      default: AurelienLourot
    - name: github_password
      prompt: GitHub password
      private: yes
    - name: sentry_dns
      prompt: Sentry DNS (e.g. https://0123456789abcdef0123456789abcdef:0123456789abcdef0123456789abcdef@sentry.io/1234567)
      private: yes
    - name: aws_access_key_id
      prompt: AWS access key ID (e.g. ABCDEFGHIJ0123456789)
      private: no
    - name: aws_secret_access_key
      prompt: AWS secret access key (e.g. 1234567890AbCdEfGhIjKlMnOpQrStUvWxYz0123)
      private: yes
    - name: efs_fs_id
      prompt: EFS filesystem ID (e.g. fs-a0123456)
      private: no

  roles:
    - ghuser-db-client

  tasks:
    - name: Hint
      vars:
        msg: |
          EC2 instance ready. You can e.g. do:
          $ ssh -i secret.pem ubuntu@{{ inventory_hostname }}
          $ tmux new-session -s 0
          $ cd db/fetchBot/
          $ ./bot.sh
      debug:
        msg: "{{ msg.split('\n') }}"
